<a href="https://colab.research.google.com/github/Loaiyounis/PyTorch_exc/blob/main/oo_pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("hello from colab")

hello from colab


In [2]:
!nvidia-smi

Thu Oct 10 19:06:17 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   33C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

##oo.PyTorch Fundamentals

Resource: notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

If you have a question:https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.4.1+cu121


## Introduction to tensors

### Creating tensors

Pytorch tensors are created using torch.tensor()` =https://pytorch.org/docs/stable/tensors.html

In [4]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
# Get tensor back as Python int
scalar.item()

7

In [7]:
# Vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# Matrix
Matrix=torch.tensor([[7,8],[9,10]])
Matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
Matrix.ndim

2

In [12]:
Matrix[0]

tensor([7, 8])

In [13]:
Matrix[1]

tensor([ 9, 10])

In [14]:
Matrix.shape

torch.Size([2, 2])

In [15]:
# TENSOR
TENSOR=torch.tensor([[[1,2,3],
                     [3,6,9],
                     [2,4,6]]])
TENSOR


tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 6]]])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])

In [18]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 6]])

In [19]:
lo=torch.tensor([[[[1,5,9,4],
                            [4,2,5,8]],
                  [[4,3,5,7],
                             [4,4,5,6]],
                  [[4,1,5,9],
                            [4,2,5,8]],
                  [[4,3,5,7],
                            [4,4,5,6]]]])
lo

tensor([[[[1, 5, 9, 4],
          [4, 2, 5, 8]],

         [[4, 3, 5, 7],
          [4, 4, 5, 6]],

         [[4, 1, 5, 9],
          [4, 2, 5, 8]],

         [[4, 3, 5, 7],
          [4, 4, 5, 6]]]])

In [20]:
lo.shape

torch.Size([1, 4, 2, 4])

In [21]:
lo[0]

tensor([[[1, 5, 9, 4],
         [4, 2, 5, 8]],

        [[4, 3, 5, 7],
         [4, 4, 5, 6]],

        [[4, 1, 5, 9],
         [4, 2, 5, 8]],

        [[4, 3, 5, 7],
         [4, 4, 5, 6]]])

In [22]:
lo.ndim

4

### Random  tensors
Why random tensors
Random tensors are important bacause the way many neural networks learn is that they start with tensors full of random mumbers and then adjust those random number to bettwe represnt data.

`Start with random nubers -> look at data -> update random numbers -> look at data -> update random numbers`
Torch random tensors =https://pytorch.org/docs/stable/generated/torch.rand.html



In [23]:
# Create a random tensor of size(3,4)
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.5875, 0.5164, 0.2681, 0.9391],
        [0.9581, 0.0106, 0.2877, 0.8345],
        [0.0687, 0.8537, 0.9738, 0.6205]])

In [24]:
random_tensor.shape

torch.Size([3, 4])

In [25]:
random_tensor.ndim

2

In [26]:
#Create random tensor with similar shape to an image tensor
random_image_size_tensor=torch.rand(size=(3,224,224)) #Hight, Width, channels(R,G,B)
random_image_size_tensor.shape,random_image_size_tensor.ndim


(torch.Size([3, 224, 224]), 3)

### Zeroes and ones

In [27]:
#Create a tensor of all zeroes
zeros=torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [28]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

# Create a tensor of all ones

In [29]:
ones=torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [30]:
ones.dtype

torch.float32

In [31]:
random_tensor.dtype

torch.float32

### Create a range on tensors and tensors-like

In [32]:
# Use torch.range() and get depracated message, use tourch.range()
one_to_ten=torch.arange(start=1,end=11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
torch.__version__

'2.4.1+cu121'

In [34]:
#Crating tensors-like
ten_zeros=torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [35]:
me=torch.rand(2,2)
me

tensor([[0.3055, 0.8069],
        [0.5212, 0.0504]])

In [36]:
me_like=torch.zeros_like(input=me)
me_like

tensor([[0., 0.],
        [0., 0.]])

###  Tensor datatype
**Note:** Tensor datatypes is one the 2 big errors you'll run into with Python & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

Precesion in computing - https://en.wikipedia.org/wiki/Single-precision_floating-point_format

In [37]:
#Float 32 Tensor
float_32_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=None, # What type is the tensoe (e,g, float32 or float16)
                             device=None, # What device your tensor in
                             requires_grad=False) #Wheather or not to track gradients with thie tensor operations
float_32_tensor

tensor([3., 6., 9.])

In [38]:
float_32_tensor.dtype

torch.float32

In [39]:
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor


tensor([3., 6., 9.], dtype=torch.float16)

In [40]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [41]:
int_32_tensor=torch.tensor([3,6,9],dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [42]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### gitting informations frm tensors (tensor attributes)

1. Tensors not right datatype - to get datatype from a tensor, can use `tensro.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensro.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensro.devoce`


In [43]:
### Create a tensor
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.8953, 0.1288, 0.6175, 0.1769],
        [0.3503, 0.8087, 0.7225, 0.4158],
        [0.7883, 0.6574, 0.9289, 0.7138]])

In [44]:
# Find out details about sone tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on : {some_tensor.device}")

tensor([[0.8953, 0.1288, 0.6175, 0.1769],
        [0.3503, 0.8087, 0.7225, 0.4158],
        [0.7883, 0.6574, 0.9289, 0.7138]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on : cpu


In [45]:
mu_tensor=torch.tensor([4,4,5],dtype=torch.float64)
print(some_tensor)
print(f"Datatype of tensor: {mu_tensor.dtype}")
print(f"Shape of tensor: {mu_tensor.shape}")
print(f"Device tensor is on : {mu_tensor.device}")

tensor([[0.8953, 0.1288, 0.6175, 0.1769],
        [0.3503, 0.8087, 0.7225, 0.4158],
        [0.7883, 0.6574, 0.9289, 0.7138]])
Datatype of tensor: torch.float64
Shape of tensor: torch.Size([3])
Device tensor is on : cpu


from __future__ import division
## Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Substraction
* Multipilcation(element-wise)
* Division
* Matrix multiplication

In [46]:
# Create a tensor and add 10 to it
tensor=torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [47]:
# Multuply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [48]:
tensor

tensor([1, 2, 3])

In [49]:
#Substract 10
tensor -10

tensor([-9, -8, -7])

In [50]:
# Try out  PyTorch in-built functions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [51]:
torch.add(tensor,10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication in nueral networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

More information on multiplying matrices - https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are two main rules the performing matrix multiplication needs to satisfy:
1. The  **inner dimensions** must match:
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work

2. The resulting matrix has the shape of the **outer dimension*

* `(2,3) @ (3,2)`-> `(2,2)`
* `(3,2) @ (2,3)` -> `(3,3)`

In [52]:
torch.matmul(torch.rand(10,10),torch.rand(10,10))

tensor([[1.6048, 1.7799, 2.5066, 3.0942, 2.1317, 1.5759, 2.9244, 2.2467, 1.0663,
         2.5857],
        [1.8405, 2.2779, 3.4538, 3.7412, 3.2886, 2.1628, 3.4117, 3.2772, 1.9619,
         2.2659],
        [1.8734, 0.9778, 2.4088, 2.7074, 1.6366, 1.3914, 2.0455, 2.1569, 1.6057,
         1.9133],
        [2.0622, 1.9584, 3.2373, 3.5770, 2.8669, 1.8791, 3.2030, 2.9156, 1.8602,
         2.6421],
        [1.9786, 2.1619, 3.0328, 3.7861, 2.7841, 1.9062, 3.2394, 2.7062, 1.6239,
         2.5114],
        [2.3887, 2.4767, 3.4536, 3.9583, 3.3345, 1.7966, 3.4716, 3.0412, 2.4035,
         2.9273],
        [2.7060, 2.8232, 4.2961, 4.4685, 3.8202, 2.1883, 4.1290, 3.8137, 2.6322,
         3.3412],
        [3.1755, 3.6110, 4.3451, 5.7172, 4.2036, 2.7216, 4.9266, 4.1058, 2.5494,
         3.9148],
        [1.7458, 1.8226, 2.9705, 3.2047, 2.7755, 1.6732, 3.0050, 2.6879, 1.8652,
         2.4179],
        [1.6187, 1.6649, 2.5078, 2.9481, 2.5988, 1.7512, 2.5721, 2.7031, 1.6670,
         1.9524]])

In [53]:
# Elenet-wise multiplication
print(tensor ,"*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [54]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [55]:
#Matrix multiplication by hand
1*1 + 2*2+3*3

14

In [56]:
%%time
value=0
for i in range (len(tensor)):
  value+= tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.65 ms, sys: 0 ns, total: 1.65 ms
Wall time: 3.48 ms


In [57]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 32 µs, sys: 6 µs, total: 38 µs
Wall time: 41 µs


tensor(14)

### One of the most common errors in deep learning: shape errors

In [58]:
#Shapes fir multiplication
tensor_A=torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_B= torch.tensor([[7,10],
                        [8,11],
                        [9,12]])
#tensot.mm(tensor_A,tensor_B)  torch.mm is the same as torch.matmul (it's an alias for writing less code)
torch.matmul(tensor_A,tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [62]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our shape issues, we can manipulate the shape of ones of our tensors using **transpose**

A ** transpose** switched axes or dimensions of a given tensor

In [63]:
tensor_B,tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [64]:
tensor_B.T,tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [65]:
# The matrix Multiplication operation works when tensor_B is tranposed
print(f" Original shapes: Tensor_A= {tensor_A.shape} tensor_B - {tensor_B.shape}")
print(f"New shapes: tensor_A: {tensor_A.shape} (same shape) as above), tensor_B.T= {tensor_B.T.shape}")
print(f"Multiplinh: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output=torch.matmul(tensor_A,tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

 Original shapes: Tensor_A= torch.Size([3, 2]) tensor_B - torch.Size([3, 2])
New shapes: tensor_A: torch.Size([3, 2]) (same shape) as above), tensor_B.T= torch.Size([2, 3])
Multiplinh: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum, etc (tensor aggregation)

In [75]:
# Create a tensor
x= torch.arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [76]:
# Find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [77]:
# Find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [2]:
# Find the mean - Note: the torch.mean() function requires a tensor of float32 datatypr to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

NameError: name 'torch' is not defined

In [1]:
# Find the sum
torch.sum(x),x.sum()

NameError: name 'torch' is not defined

## Finding thr pesitional min and max

In [1]:
x

NameError: name 'x' is not defined

In [2]:
# Find the position in tensor that  has the minimum value with armin() -> returns index position of target tensor where tthe minimum vaclue occurs
x.argmin()

NameError: name 'x' is not defined