<a href="https://colab.research.google.com/github/Loaiyounis/PyTorch_exc/blob/main/oo_pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("hello from colab")

hello from colab


In [2]:
!nvidia-smi

Fri Oct  4 15:52:43 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   45C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

##oo.PyTorch Fundamentals

Resource: notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

If you have a question:https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [6]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.4.1+cu121


## Introduction to tensors

### Creating tensors

Pytorch tensors are created using torch.tensor()` =https://pytorch.org/docs/stable/tensors.html

In [10]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [11]:
scalar.ndim

0

In [13]:
# Get tensor back as Python int
scalar.item()

7

In [15]:
# Vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [16]:
vector.ndim

1

In [18]:
vector.shape

torch.Size([2])

In [20]:
# Matrix
Matrix=torch.tensor([[7,8],[9,10]])
Matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [21]:
Matrix.ndim

2

In [22]:
Matrix[0]

tensor([7, 8])

In [24]:
Matrix[1]

tensor([ 9, 10])

In [25]:
Matrix.shape

torch.Size([2, 2])

In [28]:
# TENSOR
TENSOR=torch.tensor([[[1,2,3],
                     [3,6,9],
                     [2,4,6]]])
TENSOR


tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 6]]])

In [29]:
TENSOR.ndim

3

In [30]:
TENSOR.shape

torch.Size([1, 3, 3])

In [31]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 6]])

In [56]:
lo=torch.tensor([[[[1,5,9,4],
                            [4,2,5,8]],
                  [[4,3,5,7],
                             [4,4,5,6]],
                  [[4,1,5,9],
                            [4,2,5,8]],
                  [[4,3,5,7],
                            [4,4,5,6]]]])
lo

tensor([[[[1, 5, 9, 4],
          [4, 2, 5, 8]],

         [[4, 3, 5, 7],
          [4, 4, 5, 6]],

         [[4, 1, 5, 9],
          [4, 2, 5, 8]],

         [[4, 3, 5, 7],
          [4, 4, 5, 6]]]])

In [57]:
lo.shape

torch.Size([1, 4, 2, 4])

In [58]:
lo[0]

tensor([[[1, 5, 9, 4],
         [4, 2, 5, 8]],

        [[4, 3, 5, 7],
         [4, 4, 5, 6]],

        [[4, 1, 5, 9],
         [4, 2, 5, 8]],

        [[4, 3, 5, 7],
         [4, 4, 5, 6]]])

In [63]:
lo.ndim

4

### Random  tensors
Why random tensors
Random tensors are important bacause the way many neural networks learn is that they start with tensors full of random mumbers and then adjust those random number to bettwe represnt data.

`Start with random nubers -> look at data -> update random numbers -> look at data -> update random numbers`
Torch random tensors =https://pytorch.org/docs/stable/generated/torch.rand.html



In [81]:
# Create a random tensor of size(3,4)
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.9854, 0.7947, 0.2978, 0.6011],
        [0.9076, 0.8817, 0.9154, 0.3479],
        [0.6716, 0.7546, 0.7307, 0.4865]])

In [82]:
random_tensor.shape

torch.Size([3, 4])

In [83]:
random_tensor.ndim

2

In [86]:
#Create random tensor with similar shape to an image tensor
random_image_size_tensor=torch.rand(size=(3,224,224)) #Hight, Width, channels(R,G,B)
random_image_size_tensor.shape,random_image_size_tensor.ndim


(torch.Size([3, 224, 224]), 3)

### Zeroes and ones

In [93]:
#Create a tensor of all zeroes
zeros=torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [94]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

# Create a tensor of all ones

In [99]:
ones=torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [100]:
ones.dtype

torch.float32

In [101]:
random_tensor.dtype

torch.float32

### Create a range on tensors and tensors-like

In [113]:
# Use torch.range() and get depracated message, use tourch.range()
one_to_ten=torch.arange(start=1,end=11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [104]:
torch.__version__

'2.4.1+cu121'

In [117]:
#Crating tensors-like
ten_zeros=torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [121]:
me=torch.rand(2,2)
me

tensor([[0.4009, 0.6022],
        [0.8142, 0.9426]])

In [128]:
me_like=torch.zeros_like(input=me)
me_like

tensor([[0., 0.],
        [0., 0.]])